export const zimbabweRoutes = [
  { origin: "Harare", destination: "Bulawayo" },
  { origin: "Harare", destination: "Mutare" },
  { origin: "Gweru", destination: "Harare" },
  { origin: "Bulawayo", destination: "Victoria Falls" },
  { origin: "Kwekwe", destination: "Harare" },
  { origin: "Harare CBD", destination: "Borrowdale" },
  { origin: "Avondale", destination: "Harare CBD" },
];

export const routeCities = [
  "Harare",
  "Bulawayo",
  "Chitungwiza",
  "Mutare",
  "Gweru",
  "Kwekwe",
  "Kadoma",
  "Masvingo",
  "Chinhoyi",
  "Marondera",
  "Norton",
  "Chegutu",
  "Zvishavane",
  "Bindura",
  "Victoria Falls",
  "Hwange",
  "Rusape",
  "Redcliff",
  "Beitbridge",
  "Kariba",
  "Karoi",
  "Gokwe",
  "Shurugwi",
  "Chiredzi",
  "Chipinge",
  "Gwanda",
  "Plumtree",
  "Mvurwi",
  "Mutoko",
  "Murehwa",
  "Mhangura",
  "Mazowe",
  "Macheke",
  "Nyanga",
  "Lupane",
  "Binga",
  "Chivhu",
  "Mberengwa",
  "Buhera",
  "Murambinda",
  "Ruwa",
  "Epworth",
  "Seke",
  "Banket",
  "Glendale",
  "Shamva",
  "Guruve",
  "Mount Darwin",
  "Centenary",
  "Concession",
  "Raffingora",
  "Kotwa",
  "Mudzi",
  "Nyamapanda",
  "Wedza",
  "Hwedza",
  "Birchenough Bridge",
  "Triangle",
  "Hippo Valley",
  "Rutendo",
  "Mucheke",
  "Mkoba",
  "Sakubva",
  "Dangamvura",
  "Mbare",
  "Highfield",
  "Kuwadzana",
  "Dzivarasekwa",
  "Warren Park",
  "Budiriro",
  "Glen View",
  "Glen Norah",
  "Hatfield",
  "Avondale",
  "Borrowdale",
  "Greendale",
  "Mabvuku",
  "Tafara",
  "Waterfalls",
];
