from __future__ import annotations


ACTIVE_PASSENGER_STATUSES = frozenset(
    {
        "SEARCHING",
        "DRIVER_ASSIGNED",
        "DRIVER_EN_ROUTE",
        "DRIVER_ARRIVED",
        "PASSENGER_CONFIRMED_BOARDING",
        "IN_PROGRESS",
    }
)

ACTIVE_DRIVER_STATUSES = frozenset(
    {
        "DRIVER_ASSIGNED",
        "DRIVER_EN_ROUTE",
        "DRIVER_ARRIVED",
        "PASSENGER_CONFIRMED_BOARDING",
        "IN_PROGRESS",
    }
)

FINAL_STATUSES = frozenset(
    {
        "COMPLETED",
        "CANCELLED_BY_PASSENGER",
        "CANCELLED_BY_DRIVER",
        "CANCELLED_BY_ADMIN",
        "NO_DRIVER_FOUND",
    }
)

TRANSITIONS = {
    "SEARCHING": frozenset(
        {"DRIVER_ASSIGNED", "NO_DRIVER_FOUND", "CANCELLED_BY_PASSENGER", "CANCELLED_BY_ADMIN"}
    ),
    "DRIVER_ASSIGNED": frozenset(
        {"DRIVER_EN_ROUTE", "DRIVER_ARRIVED", "CANCELLED_BY_PASSENGER", "CANCELLED_BY_DRIVER", "CANCELLED_BY_ADMIN"}
    ),
    "DRIVER_EN_ROUTE": frozenset(
        {"DRIVER_ARRIVED", "CANCELLED_BY_PASSENGER", "CANCELLED_BY_DRIVER", "CANCELLED_BY_ADMIN"}
    ),
    "DRIVER_ARRIVED": frozenset(
        {"PASSENGER_CONFIRMED_BOARDING", "CANCELLED_BY_PASSENGER", "CANCELLED_BY_DRIVER", "CANCELLED_BY_ADMIN"}
    ),
    "PASSENGER_CONFIRMED_BOARDING": frozenset(
        {"IN_PROGRESS", "CANCELLED_BY_PASSENGER", "CANCELLED_BY_DRIVER", "CANCELLED_BY_ADMIN"}
    ),
    "IN_PROGRESS": frozenset({"COMPLETED", "CANCELLED_BY_ADMIN"}),
}
