import { Pressable, StyleSheet, Text, View } from "react-native";
import { MaterialCommunityIcons } from "@expo/vector-icons";
import { useRouter } from "expo-router";

import { Avatar } from "../../components/ui/Avatar";
import { Screen } from "../../components/ui/Screen";
import { v2Theme } from "../../constants/v2Theme";
import { useMerchantRestaurant } from "../../contexts/MerchantRestaurantContext";
import { useCurrentUser } from "../../hooks/useCurrentUser";
import { logoutToGuest } from "../../services/authService";

export default function MerchantAccountScreen() {
  const router = useRouter(); const { user } = useCurrentUser(); const merchant = useMerchantRestaurant(); const store = merchant.selected; const productParam = { product: "merchant" };
  async function signOut() { await logoutToGuest(router); }
  return <Screen title="Account" navRole="merchant"><View style={styles.profile}><Avatar name={user?.name || "Merchant"} imageUri={user?.profile_photo_url} size={72} /><View style={styles.flex}><Text style={styles.name}>{user?.name || "Merchant"}</Text><Text style={styles.meta}>{user?.email || "Email not added"}</Text><Text style={styles.meta}>{user?.phone || "Phone not added"}</Text></View><Pressable accessibilityRole="button" onPress={() => router.push({ pathname: "/(shared)/edit-profile", params: productParam } as never)} style={styles.edit}><MaterialCommunityIcons name="pencil-outline" size={20} color={v2Theme.colors.ink} /></Pressable></View><View style={styles.business}><View style={styles.businessIcon}><MaterialCommunityIcons name="storefront-outline" size={27} color={v2Theme.colors.brandStrong} /></View><View style={styles.flex}><Text style={styles.businessName}>{store?.name || "Business onboarding"}</Text><Text style={styles.businessState}>{store ? `${store.status.replaceAll("_", " ")} · ${store.address}` : "Add a restaurant to begin review"}</Text></View></View><Section title="Business"><Pressable accessibilityRole="button" onPress={() => store ? router.push(`/(merchant)/restaurant/${store.id}` as never) : router.push("/(merchant)/new" as never)}><Row icon="briefcase-outline" title="Merchant & business profile" value={store?.business_registration_number || "Business registration and contacts"} chevron /></Pressable><Pressable accessibilityRole="button" onPress={() => router.push("/(merchant)/store" as never)}><Row icon="clock-outline" title="Store operations" value="Location, hours and order availability" chevron /></Pressable></Section><Section title="Settings & support"><Pressable accessibilityRole="button" onPress={() => router.push({ pathname: "/(shared)/settings", params: productParam } as never)}><Row icon="cog-outline" title="Account & notifications" value="Privacy, account and alerts" chevron /></Pressable><Pressable accessibilityRole="button" onPress={() => router.push({ pathname: "/(shared)/support", params: productParam } as never)}><Row icon="lifebuoy" title="Merchant support" value="Orders, menu and account help" chevron /></Pressable><Pressable accessibilityRole="button" onPress={() => router.push({ pathname: "/(shared)/safety", params: productParam } as never)}><Row icon="alert-decagram-outline" title="Report an issue" value="Safety and operational reports" chevron /></Pressable></Section><Pressable accessibilityRole="button" onPress={signOut} style={({ pressed }) => [styles.logout, pressed && styles.pressed]}><MaterialCommunityIcons name="logout" size={21} color="#FFFFFF" /><Text style={styles.logoutText}>Logout</Text></Pressable></Screen>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text><View style={styles.card}>{children}</View></View>; }
function Row({ icon, title, value, chevron }: { icon: keyof typeof MaterialCommunityIcons.glyphMap; title: string; value: string; chevron?: boolean }) { return <View style={styles.row}><View style={styles.rowIcon}><MaterialCommunityIcons name={icon} size={21} color={v2Theme.colors.ink} /></View><View style={styles.flex}><Text style={styles.rowTitle}>{title}</Text><Text style={styles.rowValue}>{value}</Text></View>{chevron ? <MaterialCommunityIcons name="chevron-right" size={21} color={v2Theme.colors.inkTertiary} /> : null}</View>; }
const styles = StyleSheet.create({ flex: { flex: 1 }, profile: { flexDirection: "row", alignItems: "center", gap: 13 }, name: { color: v2Theme.colors.ink, fontSize: 23, fontWeight: "900" }, meta: { color: v2Theme.colors.inkSecondary, fontSize: 10, marginTop: 3 }, edit: { width: 43, height: 43, borderRadius: 15, backgroundColor: v2Theme.colors.surface, alignItems: "center", justifyContent: "center" }, business: { borderRadius: 24, backgroundColor: v2Theme.colors.brandSofter, padding: 14, flexDirection: "row", alignItems: "center", gap: 11 }, businessIcon: { width: 51, height: 51, borderRadius: 18, backgroundColor: v2Theme.colors.brandSoft, alignItems: "center", justifyContent: "center" }, businessName: { color: v2Theme.colors.ink, fontSize: 15, fontWeight: "900" }, businessState: { color: v2Theme.colors.inkSecondary, fontSize: 9, lineHeight: 14, marginTop: 3 }, section: { gap: 8 }, sectionTitle: { color: v2Theme.colors.ink, fontSize: 18, fontWeight: "900" }, card: { borderRadius: 23, backgroundColor: v2Theme.colors.surface, overflow: "hidden" }, row: { minHeight: 69, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", gap: 10, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: v2Theme.colors.line }, rowIcon: { width: 41, height: 41, borderRadius: 14, backgroundColor: v2Theme.colors.surfaceMuted, alignItems: "center", justifyContent: "center" }, rowTitle: { color: v2Theme.colors.ink, fontSize: 11, fontWeight: "900" }, rowValue: { color: v2Theme.colors.inkSecondary, fontSize: 9, marginTop: 2 }, logout: { minHeight: 56, borderRadius: 18, backgroundColor: v2Theme.colors.danger, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 9 }, logoutText: { color: "#FFFFFF", fontSize: 13, fontWeight: "900" }, pressed: { opacity: 0.72 } });
