import { Pressable, StyleSheet, Text, View } from "react-native";
import { MaterialCommunityIcons } from "@expo/vector-icons";
import { useFocusEffect } from "expo-router";
import { useCallback, useState } from "react";

import { LoadingState } from "../../components/states/LoadingState";
import { Screen } from "../../components/ui/Screen";
import { v2Theme } from "../../constants/v2Theme";
import { useMerchantRestaurant } from "../../contexts/MerchantRestaurantContext";
import { getMerchantInsights } from "../../services/merchantService";
import { MerchantInsights } from "../../types/merchant.types";

type Period = "today" | "week" | "month";
export default function MerchantInsightsScreen() {
  const merchant = useMerchantRestaurant();
  const [data, setData] = useState<MerchantInsights | null>(null);
  const [period, setPeriod] = useState<Period>("week");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { if (!merchant.selected) { setData(null); setLoading(false); return; } try { setError(null); setData(await getMerchantInsights(merchant.selected.id)); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load insights."); } finally { setLoading(false); } }, [merchant.selected]);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const summary = data?.periods[period]; const max = Math.max(0, ...(data?.weekly_chart || []).map((point) => point.recorded_sales_usd));
  return <Screen title="Insights" navRole="merchant" onRefresh={load} refreshing={loading}><View style={styles.heading}><Text style={styles.eyebrow}>ACTUAL ORDER DATA</Text><Text style={styles.title}>Insights</Text><Text style={styles.body}>{merchant.selected?.name || "Choose a restaurant"}</Text></View><View style={styles.tabs}><Tab label="Today" active={period === "today"} onPress={() => setPeriod("today")} /><Tab label="Week" active={period === "week"} onPress={() => setPeriod("week")} /><Tab label="Month" active={period === "month"} onPress={() => setPeriod("month")} /></View>{loading ? <LoadingState label="Calculating restaurant performance…" /> : null}{error ? <Pressable accessibilityRole="button" onPress={load} style={styles.error}><Text style={styles.errorText}>{error}</Text><Text style={styles.retry}>Retry</Text></Pressable> : null}{data && summary ? <><View style={styles.hero}><Text style={styles.heroLabel}>{period.toUpperCase()} RECORDED SALES</Text><Text style={styles.total}>${summary.recorded_sales_usd.toFixed(2)}</Text><Text style={styles.heroBody}>Completed cash-on-delivery orders only.</Text><View style={styles.metrics}><Metric label="ORDERS" value={String(summary.orders)} /><Metric label="COMPLETED" value={String(summary.completed_orders)} /><Metric label="AVG PREP" value={data.average_preparation_minutes != null ? `${data.average_preparation_minutes} min` : "Not enough data"} /></View></View><View style={styles.chartCard}><View style={styles.chartHeader}><Text style={styles.sectionTitle}>Recorded sales · 7 days</Text><MaterialCommunityIcons name="chart-box-outline" size={22} color={v2Theme.colors.brandStrong} /></View><View style={styles.chart}>{data.weekly_chart.map((point) => <View key={point.date} style={styles.column}><View style={styles.track}><View style={[styles.bar, { height: max > 0 ? Math.max(3, Math.round((point.recorded_sales_usd / max) * 88)) : 3 }]} /></View><Text style={styles.day}>{new Date(`${point.date}T12:00:00`).toLocaleDateString(undefined, { weekday: "narrow" })}</Text></View>)}</View></View><View style={styles.grid}><Stat icon="receipt-text-check-outline" label="All orders" value={String(data.total_orders)} /><Stat icon="check-decagram-outline" label="Accepted" value={String(data.accepted_orders)} /><Stat icon="bike-fast" label="Delivered" value={String(data.completed_orders)} /><Stat icon="close-circle-outline" label="Closed" value={String(data.rejected_or_cancelled_orders)} /></View><View style={styles.notice}><MaterialCommunityIcons name="cash-check" size={22} color={v2Theme.colors.inkSecondary} /><Text style={styles.noticeText}>Orders currently use cash on delivery. Sales are recorded after delivery, but no platform payout or settlement history is connected.</Text></View></> : null}</Screen>;
}
function Tab({ label, active, onPress }: { label: string; active: boolean; onPress: () => void }) { return <Pressable accessibilityRole="tab" accessibilityState={{ selected: active }} onPress={onPress} style={[styles.tab, active && styles.tabActive]}><Text style={[styles.tabText, active && styles.tabTextActive]}>{label}</Text></Pressable>; }
function Metric({ label, value }: { label: string; value: string }) { return <View style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text numberOfLines={1} style={styles.metricValue}>{value}</Text></View>; }
function Stat({ icon, label, value }: { icon: keyof typeof MaterialCommunityIcons.glyphMap; label: string; value: string }) { return <View style={styles.stat}><MaterialCommunityIcons name={icon} size={22} color={v2Theme.colors.brandStrong} /><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ heading: { gap: 3 }, eyebrow: { color: v2Theme.colors.brandStrong, fontSize: 9, fontWeight: "900", letterSpacing: 1.1 }, title: { color: v2Theme.colors.ink, fontSize: 31, fontWeight: "900", letterSpacing: -1 }, body: { color: v2Theme.colors.inkSecondary, fontSize: 10 }, tabs: { flexDirection: "row", borderRadius: 16, backgroundColor: v2Theme.colors.surfaceMuted, padding: 4, gap: 4 }, tab: { flex: 1, minHeight: 42, borderRadius: 13, alignItems: "center", justifyContent: "center" }, tabActive: { backgroundColor: v2Theme.colors.surface }, tabText: { color: v2Theme.colors.inkSecondary, fontSize: 9, fontWeight: "900" }, tabTextActive: { color: v2Theme.colors.ink }, error: { borderRadius: 17, backgroundColor: v2Theme.colors.dangerSoft, padding: 12, flexDirection: "row", gap: 9 }, errorText: { flex: 1, color: v2Theme.colors.danger, fontSize: 10, fontWeight: "700" }, retry: { color: v2Theme.colors.danger, fontSize: 10, fontWeight: "900" }, hero: { borderRadius: 27, backgroundColor: v2Theme.colors.ink, padding: 18, gap: 7 }, heroLabel: { color: "#8FE6AE", fontSize: 8, fontWeight: "900", letterSpacing: 1 }, total: { color: "#FFFFFF", fontSize: 40, fontWeight: "900", letterSpacing: -1.4 }, heroBody: { color: "rgba(255,255,255,0.58)", fontSize: 9 }, metrics: { flexDirection: "row", gap: 7, marginTop: 7 }, metric: { flex: 1, borderRadius: 15, backgroundColor: "rgba(255,255,255,0.08)", padding: 9, gap: 3 }, metricLabel: { color: "rgba(255,255,255,0.38)", fontSize: 6, fontWeight: "900" }, metricValue: { color: "#FFFFFF", fontSize: 10, fontWeight: "900" }, chartCard: { borderRadius: 24, backgroundColor: v2Theme.colors.surface, padding: 14, gap: 14 }, chartHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, sectionTitle: { color: v2Theme.colors.ink, fontSize: 16, fontWeight: "900" }, chart: { height: 120, flexDirection: "row", alignItems: "flex-end", gap: 7 }, column: { flex: 1, alignItems: "center", gap: 5 }, track: { height: 92, width: "100%", borderRadius: 8, backgroundColor: v2Theme.colors.surfaceMuted, justifyContent: "flex-end", overflow: "hidden" }, bar: { width: "100%", borderRadius: 8, backgroundColor: v2Theme.colors.brand }, day: { color: v2Theme.colors.inkSecondary, fontSize: 8, fontWeight: "900" }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, stat: { width: "48%", flexGrow: 1, minHeight: 112, borderRadius: 22, backgroundColor: v2Theme.colors.surface, padding: 13, gap: 5 }, statValue: { color: v2Theme.colors.ink, fontSize: 22, fontWeight: "900" }, statLabel: { color: v2Theme.colors.inkSecondary, fontSize: 9, fontWeight: "800" }, notice: { borderRadius: 20, backgroundColor: v2Theme.colors.brandSofter, padding: 13, flexDirection: "row", gap: 9 }, noticeText: { flex: 1, color: v2Theme.colors.inkSecondary, fontSize: 10, lineHeight: 15 } });
